### PR TITLE
Issue 24 add sdk usage header

### PR DESCRIPTION
**Pull request by yrmartinez**
### Motivation

Add feature #24 

### Checklist

- [x ] Code follows coding conventions held in this repo
- [x ] Automated tests have been added
- [ x] Tests are passing
- [ ] Docu has been updated (if applicable)
- [x] Temporary settings (e.g. project ID used during development and testing) have been reverted to defaults

### How to test

Run test 'CorrectSdkVersionHeaderAdded'

### CODE REVIEW

**Comment by petrsvihlik** [comment]
Thx @yrmartinez for the PR! @JanLenoch will have a look at it soon

**Comment by Simply007** [comment]
Great @yrmartinez, thanks!

If you want to contribute to other hacktoberfest issue, feel free to pick any of the [`hacktoberfest`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Akentico+label%3Ahacktoberfest+archived%3Afalse+) labeled issues.

**Comment by Simply007** [comment]
@yrmartinez - I have just refactored the tests to be placed on the placed on the right place: #28

**Comment by Simply007** [comment]
Hey @yrmartinez,

we would like to thank you for contributing to Kentico's open-source project. As a sign of our appreciation, we would like to send you some [Kentico Developer Community SWAG](https://twitter.com/PetrSvihlik/status/1059776942537392129)!

Please fill out your [postal address](https://goo.gl/forms/gRnURSDlXMX4ctRZ2) if you are interested.

_This comment was automatically generated. If you've submitted more than one pull request, it's OK to fill out the form just once._

Kentico Developer Community

_If there’s anything we can do to help, please don’t hesitate to reach out to us at developerscommunity@kentico.com_

**Pull request merged**
