### PR TITLE
Fix retry policy and add some unit tests for that.

### PR DESCRIPTION
**Pull request by weng271190436**
Use the Polly library to implement retry.

Imitating this implementation https://github.com/Kentico/delivery-sdk-net/pull/115/files#diff-4534083b4c5a926a7c56af08b5d6fe00

### Motivation

Improve the retry policy #4 
ContentManagementHttpClient Re-use of HttpRequestMessage #26 

### Question

I got rid of a test in ContentManagementHttpClientTests.cs called SendAsync_AddCorrectSDKTreackingHeader because I can't think of a way to test that in my new implementation of ContentManagementHttpClient.SendAsync(). In the new implementation, no HttpRequestMessage is passed into SendAsync() because SendAsync() needs to construct new HttpRequestMessage on each retry as HttpRequestMessage cannot be reused.

Is there a good way to do this so that i don't need to get rid of the test?

### CODE REVIEW

**Comment by petrsvihlik** [comment]
Hey @weng271190436 , thanks for the PR, we're on it :)

**Comment by weng271190436** [comment]
> Hey @weng271190436 , thanks for the PR, we're on it :)

Thanks! Looking forwards to your review.

**Comment by petrsvihlik** [comment]
Note to myself:
- we'll probably need to regenerate test fixtures using `TestUtils.ts LiveEndPoint_SaveToFileSystem`. more info in UX-592

**Comment by petrsvihlik** [comment]
Great job @weng271190436 !! I did just a few small adjustments. Your work will help our fellow developers a lot so thanks very much!

If you're interested in more .NET issues, you can take a look at https://github.com/orgs/Kentico/projects/2.

https://github.com/Kentico/cloud-sample-app-net/issues/13 for instance, would help us a lot.

**Pull request merged**
